name: NEBULA

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  nebula:
    name: nebula
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"


      - run: node nebula:app.js
