name: Run app.js

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-app-js:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 必要な Node.js のバージョンを指定

      # 依存関係をインストール
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      # app.js を実行
      - name: Run app.js
        run: |
          node app.js
